// Build the standalone Windows installer executable (zen-install.exe).
//
// Pipeline:
//   1. Embed the zen/ package files (engine, mod, vendored loader) into
//      src/zen/generated/embedded.ts so the exe is fully self-contained.
//   2. Bundle src/zen/cli.ts (+ installer.ts) into a single CJS file (esbuild).
//   3. Build a Node Single Executable Application (SEA) blob and inject it into
//      a copy of node.exe with postject.
//   4. Restore the embedded.ts stub so the working tree stays clean.
//
// Requires: Node >= 22 (SEA), esbuild, postject. Run: npm run build-installer

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const TMP = path.join(ROOT, '.tmp-build');
const OUT_DIR = path.join(ROOT, 'dist-zen');
const EXE = path.join(OUT_DIR, 'zen-install.exe');

// Must stay in sync with PACKAGE_FILE_LIST in src/zen/installer.ts
const PACKAGE_FILE_LIST = [
  'uc/import.uc.mjs',
  'uc/rss-sync.uc.mjs',
  'mod/chrome.css',
  'mod/preferences.json',
  'loader/program/config.js',
  'loader/program/defaults/pref/config-prefs.js',
  'loader/profile/chrome/utils/boot.sys.mjs',
  'loader/profile/chrome/utils/chrome.manifest',
  'loader/profile/chrome/utils/fs.sys.mjs',
  'loader/profile/chrome/utils/module_loader.mjs',
  'loader/profile/chrome/utils/uc_api.sys.mjs',
  'loader/profile/chrome/utils/utils.sys.mjs',
];

const EMBEDDED_TS = path.join(ROOT, 'src', 'zen', 'generated', 'embedded.ts');
const STUB = `// Generated by scripts/build_installer.mjs before bundling the executable —
// this stub keeps \`tsc\` happy in a fresh checkout. Do not edit by hand.
export const embeddedPackageFiles: Record<string, string> = {};
`;

function step(msg) {
  console.log(`[build] ${msg}`);
}

// 1. Embed package files -----------------------------------------------------
step('embedding package files');
const embedded = {};
for (const rel of PACKAGE_FILE_LIST) {
  const full = path.join(ROOT, 'zen', ...rel.split('/'));
  embedded[rel] = fs.readFileSync(full, 'utf8');
}
const stubBefore = fs.existsSync(EMBEDDED_TS) ? fs.readFileSync(EMBEDDED_TS, 'utf8') : null;
fs.writeFileSync(
  EMBEDDED_TS,
  `// Generated by scripts/build_installer.mjs — do not edit.\nexport const embeddedPackageFiles: Record<string, string> = ${JSON.stringify(embedded, null, 2)};\n`
);

let failed = false;
try {
  // 2. Bundle -----------------------------------------------------------------
  step('bundling with esbuild');
  fs.mkdirSync(TMP, { recursive: true });
  const esbuildBin = path.join(ROOT, 'node_modules', 'esbuild', 'bin', 'esbuild');
  execFileSync(process.execPath, [esbuildBin,
    path.join(ROOT, 'src', 'zen', 'cli.ts'),
    '--bundle',
    '--platform=node',
    '--format=cjs',
    '--target=node22',
    '--outfile=' + path.join(TMP, 'zen-install.cjs'),
    '--log-level=warning',
  ], { stdio: 'inherit' });

  // 3. SEA --------------------------------------------------------------------
  step('building SEA blob');
  const blob = path.join(TMP, 'zen-install.blob');
  fs.writeFileSync(
    path.join(TMP, 'sea-config.json'),
    JSON.stringify(
      {
        main: path.join(TMP, 'zen-install.cjs'),
        output: blob,
        disableExperimentalSEAWarning: true,
      },
      null,
      2
    )
  );
  execFileSync(process.execPath, ['--experimental-sea-config', path.join(TMP, 'sea-config.json')], {
    stdio: 'inherit',
  });

  // 4. Inject ------------------------------------------------------------------
  step('injecting into ' + EXE);
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.copyFileSync(process.execPath, EXE);
  const postjectBin = path.join(ROOT, 'node_modules', 'postject', 'dist', 'cli.js');
  execFileSync(process.execPath, [postjectBin,
    EXE,
    'NODE_SEA_BLOB',
    blob,
    '--sentinel-fuse',
    'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
  ], { stdio: 'inherit' });

  const sizeMb = (fs.statSync(EXE).size / 1024 / 1024).toFixed(1);
  step(`done: ${EXE} (${sizeMb} MB)`);
} catch (err) {
  failed = true;
  console.error('[build] FAILED:', err.message);
  process.exitCode = 1;
} finally {
  // 5. Restore the stub ---------------------------------------------------------
  fs.writeFileSync(EMBEDDED_TS, stubBefore ?? STUB);
  if (!failed) {
    console.log('[build] embedded.ts stub restored');
  }
}
